### ISSUE TITLE
Are the Affiliation values lower case?

### ISSUE THREAD

**Issue by trsau** [REFEDS/eduperson#2]
The definition for the Affiliation attributes states that EQUALITY is caseIgnoreMatch that tends to indicate that values with any case are fine, e.g. staff == STAFF == Staff. However all or the Permissible values are in lower case which is telling me that staff != STAFF != Staff?

We (in the AAF) now know that many IdPs in the UK Fed provide affiliations in whatever case suites them rather than providing only the lowercase version. We have modified the service that relies on these values to convert them to all lower. An additional note may be required?

As a side note, in the Notes there are instances of values being shown with uppercase first letters, both at the start of sentences. "Member" at the start of the 3rd para, and "Library-walk-in:" in the 9th para for eduPersonAffiliation. Should these be all lower even though the start a sentence, I expect some editor may have caused this?

**Comment by alanbuxey** [comment]
the main examples list them all lowercase but they are indeed case insensitive. A single federation may find values all lowercase if their members have all followed documentation provided by the federation that has them listed or provides examples/templates. likewise, it may be common in a federation for them all to start with a single capital letter. some federations are exclusively all in capitals too.
(and the rest are a mixed bunch)

however, an additional note to highlight this is probably worthwhile

**Comment by hlflanagan** [comment]
The definition for eduPersonAffiliation states that case should be ignored. 
"EQUALITY caseIgnoreMatch"
