### ISSUE TITLE
ORCID example needs updating

### ISSUE THREAD

**Issue by alanbuxey** [REFEDS/eduperson#3]
in the latest eduPerson spec

https://wiki.refeds.org/display/STAN/eduPerson+2020-01#eduPerson2020-01-eduPersonOrcid 

has still an example http://orcid.org/

https://orcid.org/blog/2017/11/02/canonical-form-orcid-id-coming recommends https://orcid.org/

**Comment by hlflanagan** [comment]
Fixed
