### ISSUE TITLE
eduPerson for Active Directory

### ISSUE THREAD

**Issue by lonoak** [REFEDS/eduperson#9]
Hi,

   I have frequent requests of LDIF files of the eduPerson Schema for Active Directory. Other than the version available here:

https://spaces.at.internet2.edu/display/macedir/Active+Directory+eduPerson

which dates from 2013, is any other more recent version of the schema available for AD?

Thanks.

**Comment by jbabbrtg** [comment]
The wiki page includes through 201705.  I just filled a PR with 202111 along with fixing formatting so its friendly to ldifde. Copy/paste out of the wiki is unfortunately not friendly. 

https://github.com/REFEDS/eduperson/pull/14

**Comment by hlflanagan** [comment]
See https://github.com/REFEDS/eduperson/blob/master/schema/activedirectory/eduPerson.adschema.ldf (recently updated)
